name: PaintballAdvanced
main: me.adrian.paintball.PaintballPlugin
version: 1.0
api-version: 1.20
commands:
  pa:
    description: Comando principal de Paintball
    usage: /pa
  paadmin:
    description: Panel de administrador
    usage: /paadmin
