name: PaintballPlugin
main: me.adrian.paintball.PaintballPlugin
version: 1.0
api-version: 1.21
commands:
  pa:
    description: Paintball main command
  paadmin:
    description: Paintball admin commands
