name: PaintballPlugin
main: me.adrian.paintball.PaintballPlugin
version: 1.0
api-version: 1.21
commands:
  pa:
    description: Comando principal de Paintball
    usage: /pa <subcomando>
  paadmin:
    description: Comandos de administrador de Paintball
    usage: /paadmin <subcomando>
permissions:
  paintball.admin:
    description: Permiso de administrador
    default: op
