name: PaintballMinigame
version: 1.0
main: me.adrian.paintball.PaintballPlugin
api-version: 1.21
commands:
  pa:
    description: Comando principal de Paintball
    usage: /pa <subcomando>
  paadmin:
    description: Comandos de administración
    usage: /paadmin <subcomando>
